<?php

namespace Alt87\Bundle\TodoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getCompletedTasks()
    {
        return $this->getEntityManager()->findByComplete(1);
    }
}
